AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
    sam-app

    Sample SAM Template for sam-app

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
    Function:
        Timeout: 10
        Environment:
            Variables:
                DEBUG: 1
                REDIS_HOST: host.docker.internal
                REDIS_PORT: 6379
                REDIS_PASSWORD: ""
                DYNAMO_ENDPOINT_URL: http://host.docker.internal:8000/


Resources:
    ApiFunction:
        Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
        Properties:
            CodeUri: api_function/
            Handler: app.lambda_handler
            Runtime: python3.6
            Events:
                HelloWorld:
                    Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
                    Properties:
                        Path: /api_function
                        Method: get
    CallApiFunction:
        Type: AWS::Serverless::Function 
        Properties:
            CodeUri: function_to_call_api_function/
            Handler: app.lambda_handler
            Runtime: python3.6
            Events:
                HelloWorld:
                    Type: Api 
                    Properties:
                        Path: /call_api_function
                        Method: get
    CallDockerFunction:
        Type: AWS::Serverless::Function
        Properties:
            CodeUri: function_to_call_docker/
            Handler: app.lambda_handler
            Runtime: python3.6
            Events:
                HelloWorld:
                    Type: Api
                    Properties:
                        Path: /call_docker
                        Method: get
    CallFunctionFunction:
        Type: AWS::Serverless::Function
        Properties:
            CodeUri: function_to_call_function/
            Handler: app.lambda_handler
            Runtime: python3.6
            Events:
                HelloWorld:
                    Type: Api
                    Properties:
                        Path: /call_function
                        Method: get
    CallDebugFunction:
        Type: AWS::Serverless::Function
        Properties:
            CodeUri: function_to_debug/
            Handler: app.lambda_handler
            Runtime: python3.6
            Events:
                HelloWorld:
                    Type: Api
                    Properties:
                        Path: /call_debug
                        Method: get

Outputs:

    # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
    # Find out more about other implicit resources you can reference within SAM
    # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
    ApiFunctionApi:
      Description: "API Gateway endpoint URL for Prod stage for Hello World function"
      Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/api_function/"

    ApiFunctionFunction:
      Description: "Hello World Lambda Function ARN"
      Value: !GetAtt ApiFunction.Arn

    ApiFunctionIamRole:
      Description: "Implicit IAM Role created for Hello World function"
      Value: !GetAtt ApiFunctionRole.Arn
